---
title: "LiveOcean vs. TH042 Comparisons"
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

# Setup

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork)
library(scales)
library(ggrepel)
library(readxl)
library(here)
library(mgcv)
library(gratia)
library(ggpmisc)
```

```{r}
# Import OME data
OME <- envData <- read_csv(here("PMEL-Data", "EnvironmentalDataset1_copy.csv")) %>% # full data with 2023
  filter(!is.na(DO)) %>% 
  mutate(Date_UTC = date)
# Import LiveOcean data (turned into dataframe in NetCDF_to_DF.R)
model_alldepths <- read_csv(here("LiveOceanTH042_2021_2023.csv")) %>% 
  mutate(DateMatch = Date_UTC) # for join later
model <- model_alldepths %>% 
  filter(s_rho < -0.92 & s_rho > -0.97) 

model_37m <- read_csv(here("LiveOcean_TH042_2021_2023_DepthClean.csv")) %>% 
  mutate(DateMatch = Date_UTC) # this is the one I'm actually using

OME_match <- OME %>% 
  mutate(DateMatch = round_date(date, unit = "10 minutes")) # looks good, we have 10, 20, 30, 40, 50, 00 every hour


# s_rho is a depth coordinate system where the bottom is -1 and the surface is 0
# https://www.mathworks.com/matlabcentral/answers/2056554-from-s-coordinate-at-rho-points-to-depth
# i do Not wanna do all that math. mooring is close to the bottom so let's use -0.95 rho
```
```{r}
ggplot(data = OME, aes(x = Date_UTC, y = DO)) +
  geom_line(color = "orange", size = 0.5) +
  geom_line(data = model_37m, aes(x = Date_UTC, y = Oxygen_mg_L),
            color = "navyblue", size = 0.5, alpha = 0.5) +
  labs(title = "TH042 Mooring vs. LiveOcean Model (DO)", caption = "Mooring in orange, model in dark blue. 37m depth.") +
  theme_bw() 

ggsave(here("LiveOcean_Plots_37", "Mooring_vs_Model_DO_37.png"))

ggplot(data = OME, aes(x = Date_UTC, y = temperature)) +
  geom_line(color = "orange", size = 0.5) +
  geom_line(data = model_37m, aes(x = Date_UTC, y = Temp_C),
            color = "navyblue", size = 0.5, alpha = 0.5) +
  labs(title = "TH042 Mooring vs. LiveOcean Model (Temp)", caption = "Mooring in orange, model in dark blue. 37m depth.") +
  theme_bw() 

ggsave(here("LiveOcean_Plots_37", "Mooring_vs_Model_Temp_37.png"))
```

## Regression

```{r}
compare <- left_join(OME_match, model_37m, by = join_by(DateMatch))

compare2 <- compare %>% 
  dplyr::select(c(source, year, 
                    temperature, DO, DateMatch,
                    Temp_C, Oxygen_mg_L)) %>%
  dplyr::rename(Temp_Mooring = temperature, 
                DO_Mooring = DO, 
                Temp_Model = Temp_C, 
                DO_Model = Oxygen_mg_L) # for clarity
  
  # Compare temp predictions
  temp_mod <- lm(Temp_Mooring ~ Temp_Model, compare2)
  #print(summary(temp_mod))
  rsq <- summary(temp_mod)$r.squared
  print(paste("Temp R squared: ", rsq))
  t_RMSE <- sqrt(mean(temp_mod$residuals^2))
  t_bias <- mean(temp_mod$residuals)

  print(ggplot(compare2, aes(x = Temp_Mooring, y = Temp_Model)) +
          geom_point() +
          geom_smooth(method = "lm") +
          ggtitle("Temperature at 37 m") +
          annotate("text", x = 9, y = 12, 
                   label = paste("R^2 = ", round(rsq, 3)), size = 10) +
          annotate("text", x = 9, y = 11, 
                   label = paste("RMSE = ", round(t_RMSE, 3)), size = 10) +
          theme_bw())
  
  ggsave("Temp_LiveOcean_37.png", 
         path = here("LiveOcean_Plots_37"),
         width = 3000, height = 2500, units = "px")
  
  # Compare DO predictions
  ox_mod <- lm(DO_Mooring ~ DO_Model, compare2)
  #print(summary(ox_mod))
  o_rsq <- summary(ox_mod)$r.squared
  o_RMSE <- sqrt(mean(ox_mod$residuals^2))
  print(paste("DO R squared: ", o_rsq))

  print(ggplot(compare2, aes(x = DO_Mooring, y = DO_Model)) +
          geom_point() +
          geom_smooth(method = "lm") +
          ggtitle("Oxygen at 37 m") +
          annotate("text", x = 7, y = 1, 
                   label = paste("R^2 = ", round(o_rsq, 3)), size = 10) +
          annotate("text", x = 7, y = 0.5, 
                   label = paste("RMSE = ", round(o_RMSE, 3)), size = 10) +
          theme_bw())
  
  ggsave(filename = "Oxygen_LiveOcean_37.png", 
         path = here("LiveOcean_Plots_37"),
         width = 3000, height = 2500, units = "px")
  

```

# --Exploration--

This is old messing with z-rho

```{r}
ggplot(data = OME, aes(x = Date_UTC, y = DO)) +
  geom_line(color = "orange", size = 0.5) +
  geom_line(color = "blue", size = 0.5, data = model, aes(x = Date_UTC, y = Oxygen_mg_L)) +
  theme_bw()
```


# Hourly Plots

## All rhos

```{r}
rhos <- unique(model_alldepths$s_rho)

for (i in 1:length(rhos)) {
  print(i)
  rho = rhos[i]
  print(rho)
  
  print(ggplot(data = OME, aes(x = Date_UTC, y = DO)) +
    geom_line(color = "black", size = 0.5) +
    geom_line(color = "blue", size = 0.5, alpha = 0.2, 
              data = model_alldepths %>% filter(s_rho == rho), # filter for 1 rho
    aes(x = Date_UTC, y = Oxygen_mg_L)) +
      ggtitle(paste("s_rho = ", rho, sep = "")) +
    theme_bw()) +
    theme(text = element_text(size = 20))
  
  ggsave(filename = paste(paste("LiveOcean_s_rho", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")
}
```
## Regressions

```{r}
# Regressions of model vs mooring
s_rho_for_lm <- rhos
r_sq_temp <- c()
r_sq_ox <- c()

for (i in 1:length(rhos)) {
  rho = rhos[i]
  print(paste("s_rho = ", rho))
  
  temp <- model_alldepths %>% filter(s_rho == rho) # pull the model data for this rho
  
  compare <- left_join(OME_match, temp, by = join_by(DateMatch)) 
  compare2 <- compare %>% 
    dplyr::select(c(source, year, temperature, DO, DateMatch, s_rho, Temp_C, Oxygen_mg_L)) %>% 
    dplyr::rename(Temp_Mooring = temperature, DO_Mooring = DO, Temp_Model = Temp_C, DO_Model = Oxygen_mg_L) # for clarity
  
  # Compare temp predictions
  temp_mod <- lm(Temp_Mooring ~ Temp_Model, compare2)
  #print(summary(temp_mod))
  rsq <- summary(temp_mod)$r.squared
  print(paste("Temp R squared: ", rsq))
  r_sq_temp <- c(r_sq_temp, round(rsq, 3))
  
  print(ggplot(compare2, aes(x = Temp_Mooring, y = Temp_Model)) +
          geom_point() +
          geom_smooth(method = "lm") +
          ggtitle(paste("Temperature at ", rho)) +
          annotate("text", x = 9, y = 12, label = paste("R^2 = ", r_sq_temp), size = 10) +
          theme_bw())
  
  ggsave(filename = paste(paste("Temp_LiveOcean_s_rho", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")
  
  # Compare DO predictions
  ox_mod <- lm(DO_Mooring ~ DO_Model, compare2)
  #print(summary(ox_mod))
  o_rsq <- summary(ox_mod)$r.squared
  print(paste("DO R squared: ", o_rsq))
  r_sq_ox <- c(r_sq_ox, round(o_rsq, 3))
  
  print(ggplot(compare2, aes(x = DO_Mooring, y = DO_Model)) +
          geom_point() +
          geom_smooth(method = "lm") +
          ggtitle(paste("Oxygen at ", rho)) +
          annotate("text", x = 7, y = 1, label = paste("R^2 = ", r_sq_ox), size = 10) +
          theme_bw())
  
  ggsave(filename = paste(paste("Oxygen_LiveOcean_s_rho", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")

}

# Compare the rsq values
matches <- data.frame(s_rho_for_lm, r_sq_temp, r_sq_ox)
```

# Daily Average Plots

## All rhos

```{r}
rhos <- unique(model_alldepths$s_rho)

OME <- OME %>% 
  mutate(Day = as.Date(Date_UTC))

model_alldepths <- model_alldepths %>% 
  mutate(Day = as.Date(Date_UTC))

OME_day <- OME %>% 
  group_by(Day) %>% 
  summarize(OME_Day_Temp = mean(temperature), OME_Day_DO = mean(DO))

MOD_day <- model_alldepths %>% 
  group_by(Day, s_rho) %>% 
  summarize(MOD_Day_Temp = mean(Temp_C), MOD_Day_DO = mean(Oxygen_mg_L))

for (i in 1:length(rhos)) {
  print(i)
  rho = rhos[i]
  print(rho)
  
  print(ggplot(data = OME_day, aes(x = Day, y = OME_Day_DO)) +
    geom_line(color = "black", size = 0.5) +
    geom_line(color = "blue", size = 0.5, alpha = 0.2, 
              data = MOD_day %>% filter(s_rho == rho), # filter for 1 rho
    aes(x = Day, y = MOD_Day_DO)) +
      ggtitle(paste("s_rho = ", rho, sep = "")) +
    theme_bw()) +
    theme(text = element_text(size = 20))
  
  ggsave(filename = paste(paste("LiveOcean_s_rho_DAY", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")
}
```
## Regressions

```{r}
# Regressions of model vs mooring
s_rho_for_lm <- rhos
r_sq_temp_day <- c()
r_sq_ox_day <- c()

for (i in 1:length(rhos)) {
  rho = rhos[i]
  print(paste("s_rho = ", rho))
  
  temp <- MOD_day %>% filter(s_rho == rho) # pull the model data for this rho
  
  compare <- left_join(OME_day, temp, by = join_by(Day)) 
  compare2 <- compare %>% 
    dplyr::select(c(Day, OME_Day_Temp, OME_Day_DO, s_rho, MOD_Day_Temp, MOD_Day_DO)) 
  
  # Compare temp predictions
  temp_mod <- lm(OME_Day_Temp ~ MOD_Day_Temp, compare2)
  #print(summary(temp_mod))
  rsq <- summary(temp_mod)$r.squared
  print(paste("Temp R squared: ", rsq))
  r_sq_temp_day <- c(r_sq_temp_day, round(rsq, 3))
  
  print(ggplot(compare2, aes(x = OME_Day_Temp, y = MOD_Day_Temp)) +
          geom_point() +
          geom_smooth(method = "lm") +
          ggtitle(paste("Daily Temperature at ", rho)) +
          annotate("text", x = 9, y = 12, label = paste("R^2 = ", round(rsq, 3)), size = 10) +
          theme_bw())
  
  ggsave(filename = paste(paste("Temp_LiveOcean_s_rho_DAY", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")
  
  # Compare DO predictions
  ox_mod <- lm(OME_Day_DO ~ MOD_Day_DO, compare2)
  #print(summary(ox_mod))
  o_rsq <- summary(ox_mod)$r.squared
  print(paste("DO R squared: ", o_rsq))
  r_sq_ox_day <- c(r_sq_ox_day, round(o_rsq, 3))
  
  print(ggplot(compare2, aes(x = OME_Day_DO, y = MOD_Day_DO)) +
          geom_point() +
          geom_smooth(method = "lm") +
          ggtitle(paste("Daily Oxygen at ", rho)) +
          annotate("text", x = 7, y = 1, label = paste("R^2 = ", round(o_rsq, 3)), size = 10) +
          theme_bw())
  
  ggsave(filename = paste(paste("Oxygen_LiveOcean_s_rho_DAY", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")

}

# Compare the rsq values
matches_day <- data.frame(s_rho_for_lm, r_sq_temp_day, r_sq_ox_day)
```

# Hourly Average Plots

## All rhos

```{r}
rhos <- unique(model_alldepths$s_rho)

OME <- OME %>% 
  mutate(Date_hr = round_date(date, unit = "1 hour"))

model_alldepths <- model_alldepths

OME_hr <- OME %>% 
  group_by(Date_hr) %>% 
  summarize(OME_Hr_Temp = mean(temperature), OME_Hr_DO = mean(DO))

for (i in 1:length(rhos)) {
  print(i)
  rho = rhos[i]
  print(rho)
  
  print(ggplot(data = OME_hr, aes(x = Date_hr, y = OME_Hr_DO)) +
    geom_line(color = "black", size = 0.5) +
    geom_line(color = "blue", size = 0.5, alpha = 0.2, 
              data = model_alldepths %>% filter(s_rho == rho), # filter for 1 rho
    aes(x = Date_UTC, y = Oxygen_mg_L)) +
      ggtitle(paste("s_rho = ", rho, sep = "")) +
    theme_bw()) +
    theme(text = element_text(size = 20))
  
  ggsave(filename = paste(paste("LiveOcean_s_rho_HOUR", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")
}
```
## Regressions

```{r}
# Regressions of model vs mooring
s_rho_for_lm <- rhos
r_sq_temp_hr <- c()
r_sq_ox_hr <- c()

for (i in 1:length(rhos)) {
  rho = rhos[i]
  print(paste("s_rho = ", rho))
  
  temp <- model_alldepths %>% filter(s_rho == rho) # pull the model data for this rho
  
  compare <- left_join(OME_hr, temp, by = join_by(Date_hr == Date_UTC)) 
  compare2 <- compare %>% 
    dplyr::select(c(Day, OME_Hr_Temp, OME_Hr_DO, s_rho, Temp_C, Oxygen_mg_L))  %>% 
    dplyr::rename(MOD_Temp = Temp_C, MOD_DO = Oxygen_mg_L)
  
  # Compare temp predictions
  temp_mod <- lm(OME_Hr_Temp ~ MOD_Temp, compare2)
  #print(summary(temp_mod))
  rsq <- summary(temp_mod)$r.squared
  print(paste("Temp R squared: ", rsq))
  r_sq_temp_hr <- c(r_sq_temp_hr, round(rsq, 3))
  
  print(ggplot(compare2, aes(x = OME_Hr_Temp, y = MOD_Temp)) +
          geom_point() +
          geom_smooth(method = "lm") +
          ggtitle(paste("Hourly Temperature at ", rho)) +
          annotate("text", x = 9, y = 12, label = paste("R^2 = ", round(rsq, 3)), size = 10) +
          theme_bw())
  
  ggsave(filename = paste(paste("Temp_LiveOcean_s_rho_HOUR", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")
  
  # Compare DO predictions
  ox_mod <- lm(OME_Hr_DO ~ MOD_DO, compare2)
  #print(summary(ox_mod))
  o_rsq <- summary(ox_mod)$r.squared
  print(paste("DO R squared: ", o_rsq))
  r_sq_ox_hr <- c(r_sq_ox_hr, round(o_rsq, 3))
  
  print(ggplot(compare2, aes(x = OME_Hr_DO, y = MOD_DO)) +
          geom_point() +
          geom_smooth(method = "lm") +
          ggtitle(paste("Hourly Oxygen at ", rho)) +
          annotate("text", x = 7, y = 1, label = paste("R^2 = ", round(o_rsq, 3)), size = 10) +
          theme_bw())
  
  ggsave(filename = paste(paste("Oxygen_LiveOcean_s_rho_HOUR", rho, sep = "_"), ".png", sep = ""), 
         path = here("LiveOcean_Plots"),
         width = 3000, height = 2500, units = "px")

}

# Compare the rsq values
matches_hr <- data.frame(s_rho_for_lm, r_sq_temp_hr, r_sq_ox_hr)
```

