---
title: "Thesis Goal 1 (with 2023)"
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork)
library(scales)
library(ggrepel)
library(readxl)
library(here)
```

# Imports

```{r}
envData_pre <- read_csv(here("PMEL-Data", "EnvironmentalDataset1_copy.csv")) %>% # Mooring data
  mutate(year = as.factor(year)) %>% 
  relocate(year, .after = date) %>% 
  rename(Mooring_DO = DO)
model_37m <- read_csv(here("LiveOcean_TH042_2021_2023_DepthClean.csv")) %>% # Model data (for the 2023 gap)
  mutate(DateMatch_hr = Date_UTC) # to match with eDNA data
allReads <- read_csv(here("PMEL-Data", "FishPlusCOI_Reads_copy.csv")) %>% # non-cleaned allReads
  mutate(year = year(Date_local)) %>% 
  relocate(year, .after = Date_local) %>% 
  mutate(Species = case_when(Species == "Pseudocalanus acuspes" ~ "Pseudocalanus mimus", .default = Species)) # janky fix for the misidentification

# Reference
copepodNames <- read_csv(here("PMEL-Data", "OCNMS_Copepods_Krill_copy.csv"))
copepods <- c(unique(copepodNames$Species))
eDNAxEnvDataSat <- read_csv(here("PMEL-Data", "eDNAxEnvDataSat_copy.csv"))

# ThesisPart1.Rmd does the janky P. mimus fix for these
copepodFiltered <- read_csv(here("CopepodDetectionsFiltered.csv"))
copepodFull <- read_csv(here("CopepodDetectionsFull.csv"))

# Rounding
EnvRd <- envData_pre %>% 
  mutate(DateMatch = round_date(date, unit = "10 minutes"), # Round to the nearest 10 minutes
         DateMatch_hr = round_date(date, unit = "hour")) # Round to the nearest hour to combine with the model

envData <- full_join(EnvRd, model_37m, by = join_by(DateMatch_hr)) %>% # need this for the graphing function
  mutate(DO = Oxygen_mg_L,
         Temp = Temp_C,
         date = case_when(is.na(DateMatch) ~ DateMatch_hr,
                          .default = DateMatch)) %>% # use mooring date if available, use model date if not. for graphing function.
  relocate(DO, Temp, .after = DateMatch_hr)
```

```{r}
ggplot(envData, aes(x = date, y = DO)) + 
  geom_line(color = "gray50", size = 0.2) +
  theme_bw()
```

# Calculate eDNA index

```{r}
# First, combine PCR replicates and average
PCR_reps_combine <- function(df) {
  # print(head(df))
  
  # Separate out Sample_Name into three informational columns
  df_out <- df %>% 
    separate(Sample_Name, 
             into=c("E_no", "Cruise1", "PCR_Rep"), 
             remove=F, 
             fill = "right") %>% # sep is a regular expression which is annoying, but the default recognizes any non-alphanumeric characters so the default works here
    mutate(.)
  
  # Define which columns to group by
  id_cols1 <- colnames(df_out) # Pull out column names
  id_cols1 <- id_cols1[! id_cols1 %in% c("X", "SampleId","Sample_Name", "PCR_Rep", "pctMatch", "JV_Sample_Name", "Technical_Replicate", "nReads", "Barcode.y", "E_no", "Depth_m", "Rosette_position", "Field_Sample_Name", "Field_Notes")] # Remove SampleId and Sample_Name, as well as other things that differ by PCR replicate. Also removed E_no, Depth, and Rosette_position because they differ by multiple samples in one day (exclusive to Niskin samples). These are all the things removed from id_cols.
  print(id_cols1)
  
  df_out <- df_out %>% 
    group_by_at(id_cols1) %>% # I am using species and datetime to group, which deletes E-no but I don't think I've been using it. This should be ok.
    # dplyr::mutate(SampleId = dplyr::first(SampleId)) %>% 
    dplyr::summarize(nReads = mean(nReads)) %>% 
    relocate(nReads, .after = PI)
    
  df_out
}

allReads_PCRcomb <- PCR_reps_combine(allReads) # Spot check E1325 was correct
```

```{r}
# did PCRcomb fix dates with multiple samples?

allRP_check2 <- allReads_PCRcomb %>% 
  filter(Species == "Acartia longiremis") %>% 
  group_by(Date_local) %>% 
  dplyr::summarize(n = n())
allRP_check2

allRP_check3 <- allReads_PCRcomb %>% 
  filter(Species == "Acartia longiremis") %>% 
  arrange(Date_local)

# no b/c samples on the same day had different e-numbers
# now it does bc i ignored e-numbers! all dates should have 245 rows <3
# depth, e-no, rosette position fixed some but not all
# still problem: 2021-10-08 11:15:00
# ok so Field_Sample_Name is not always NA. Cheers.
# 2022-06-21 13:28:00 is the only one not fixed by that. whaddaya wanna bet there's a field note.
# Yup. Niskin failed leak test on Rosette position 2.
# YEEEESSSSS
```

```{r}
# Second, combine by species

id_cols <- colnames(allReads_PCRcomb) # Pull out column names
id_cols <- id_cols[! id_cols %in% c("X", "ESV", "sequence", "nReads")] # Remove ESV + nreads because those are different within species

allReads_species <- allReads_PCRcomb %>% 
  group_by_at(id_cols) %>% # group_by_at can take a vector
  dplyr::summarize(TotalnReads = sum(nReads)) %>% # Removed , avgpctMatch = mean(pctMatch) because I had to remove pctMatch to combine PCR replicates. Sum nReads results in taking the sum of all ESVs within a species
  relocate(TotalnReads, .after = PI)

write_csv(allReads_species, here("eDNA_Index_Hypoxia", "Data", "allReads_Species.csv")) # Gonna want this later

# Calculate eDNA index

# First make a unique ID column
allReads_species <- allReads_species %>% 
  mutate(Species_abbrev = sub("(\\w+)(\\S)", substring(Species, 1, 1), Species)) %>% # find word + space, replace with first letter
  relocate(Species_abbrev, .after = Species) %>% 
  mutate(ID_Ella = paste(Date_UTC, Amplicon, sep = "_")) %>% # just making unique sampleIDs until grouping by it fixes the eDNA index
  relocate(ID_Ella, .after = Species) %>% 
  mutate(ID_Ella = gsub(" ", "_", ID_Ella)) %>% 
  mutate(ID_Ella = gsub("-", "", ID_Ella)) %>%
  mutate(ID_Ella = gsub(":", "", ID_Ella))

length(unique(allReads_species$ID_Ella)) # should = 68634 because that's the length of the dataset
```

```{r}
all_index1 <- allReads_species %>%
  dplyr::group_by(ID_Ella) %>% # because sampleID & E_no had to be removed in the PCR replicate combination step
  mutate(Tot = sum(TotalnReads),
      	Row.sums = TotalnReads / Tot) %>% # calculate proportions - 0 reads/0 total = NaN, need to replace with 0 to make max() work
  relocate(c(TotalnReads, Tot, Row.sums), .after = Species) # Move it somewhere I can see the damn thing

all_eDNA_index <- all_index1 %>% 
  dplyr::group_by(Family, Genus, Species) %>%
  mutate(Row.sums = case_when(Row.sums == "NaN" ~ 0, 
                                      .default = Row.sums)) %>% # Make 0/0 = 0 and not NaN
  mutate(Colmax = max(Row.sums), Normalized.reads = Row.sums / Colmax) %>%  #transforms raw number of reads to eDNA index. Creates same divide by 0 error, so:
  mutate(Normalized.reads = case_when(Normalized.reads == "NaN" ~ 0, 
                                      .default = Normalized.reads)) %>% # Make 0/0 = 0 and not NaN
  relocate(c(Colmax, Normalized.reads), .after = Row.sums)  # Move it somewhere I can see the damn thing

# Filter to only copepods
copepod_eDNA_index <- all_eDNA_index %>% 
  filter(Species %in% copepods | Genus %in% c("Calocalanus", "Clausocalanus", "Paracalanus") | Class == "Hexanauplia") %>% 
  rename(eDNA_index = `Normalized.reads`) # to make parsing this easier

write_csv(copepod_eDNA_index, here("eDNA_Index_Hypoxia", "Data", "Copepod_eDNA_index.csv")) # Gonna want this later
```

```{r}
# Did it work?
ggplot(copepod_eDNA_index, aes(x = Date_local, y = eDNA_index, color = Species)) +
  geom_point(show.legend = F, size = 1) +
  facet_wrap(facets = vars(year(Date_local)), scales = "free_x") +
  geom_line(show.legend = F) +
  theme_bw()
```


## Combine eDNA index with environmental data

```{r}
# envData = EnvironmentalDataset1
# Based on eDNAxpO2.Rmd from summer project
# copepod_eDNA_index is still essentially a version of allReads so I can use the same code I did with allReads_Species

# Round to make join work
DetectRd <- copepod_eDNA_index %>% 
  mutate(DateMatch = round_date(Date_UTC, unit = "10 minutes"), DateMatch_hr = round_date(Date_UTC, unit = "hour")) # Spot check - looks good. 

eDNAindxEnvData <- left_join(DetectRd, EnvRd, by = join_by(DateMatch)) %>% 
  relocate(c(DateMatch, year.x, year.y, Mooring_DO, temperature), .after = ID_Ella) %>% 
  mutate(DateMatch_hr = round_date(Date_UTC, unit = "hour"))

eDNAindxEnvDataMod_pre <- left_join(eDNAindxEnvData, model_37m, by = join_by(DateMatch_hr)) %>% 
  relocate(c(Temp_C, Oxygen_mg_L), .after = temperature) %>% 
  rename(Mooring_T = temperature, Model_T = Temp_C, Model_DO = Oxygen_mg_L)

# Make one column each for temp and DO, using only the model
eDNAindxEnvDataMod <- eDNAindxEnvDataMod_pre %>% 
  mutate(DO = Model_DO,
         Temp = Model_T) %>% 
  relocate(DO, Temp, .after = Model_DO)

system("say Data Join Complete")

# Export the joined data
write_csv(eDNAindxEnvDataMod, here("eDNA_Index_Hypoxia", "Data", "Copepod_eDNAindxEnvData_Model.csv"))
```

```{r}
# Find number of copepods
eDNAindxEnvDataMod %>% 
  group_by(Family, Genus, Species) %>% 
  summarize(Reads = sum(TotalnReads))

n_species <- eDNAindxEnvDataMod %>% 
  group_by(Family, Genus, Species) %>% 
  summarize(Reads = sum(TotalnReads)) %>% 
  filter(Reads > 0) # 17
```

```{r}
# Make a version without any non-detected copepods and add presence
eDNAindxEnvDataMod_clean <- eDNAindxEnvDataMod %>% 
  filter(Colmax > 0) %>% 
  mutate(Present = case_when(TotalnReads == 0 ~ F, .default = T)) %>% 
  relocate(Present, .before = TotalnReads)
  
write_csv(eDNAindxEnvDataMod_clean, here("eDNA_Index_Hypoxia", "Data", "Copepod_eDNAindxEnvDataMod_clean.csv"))

dfsplit <- split(eDNAindxEnvDataMod_clean, eDNAindxEnvDataMod_clean$Species) # Split by species for later graphing
```

# Graphs

## Explore 


```{r}
source(here("eDNA_Index_Hypoxia", "eDNA_EnvGraphFunction.R"))


eDNAGraph_23(eDNAindxEnvDataMod_clean, 
          envCond = "DO", 
          envCondName = "Oxygen", 
          filepath = here("eDNA_Index_Hypoxia", "Plots", "eDNAxDO_mod"),
          ylab = "Dissolved Oxygen (mg/L)", 
          widthpx = 3000, # make it longer
          threshold = F,
          thresholdLvl = 2
          )
```

## DO x Temp x eDNA

```{r}
# Distinguish the zero values better in the scatterplots
# I could do this by making a custom scale....ORRRR I could just add another layer where 0 is black lol :)

for (i in 1:length(dfsplit)) { # For each species: 
    species <- dfsplit[[i]]$Species[1] # Species name 
    title <- paste(species, sep = " ", "eDNA Index vs DO & Temperature (modeled)") # Plot title
    print(title)
    
# Plot + save
    
    print( # plot this species
      ggplot(dfsplit[[i]], aes(x = Temp, 
                                    y = DO, 
                                    size = eDNA_index, color = eDNA_index)) +
        scale_color_viridis_c(option = "viridis", direction = -1) + # color
        scale_size(range = c(2, 7)) +
        geom_point(alpha = 0.5) +
        geom_point(shape = 1) + # add outline
        geom_point(data = dfsplit[[i]] %>% filter(eDNA_index == 0), 
                   aes(x = Temp, y = DO),
                   color = "black", size = 2) + # add more distinctive zeroes
        labs(x = "Temperature (C)", 
             y = "Dissolved Oxygen (mg/L)", 
             color = "eDNA Index", 
             size = "eDNA Index",
             title = title) +
        geom_hline(yintercept = 0.66, linetype = 2, 
                   color = "red", linewidth = 1) + # most die
        geom_hline(yintercept = 0.9, linetype = 2, 
                   color = "orange", linewidth = 1) + # ~50% die
        geom_hline(yintercept = 2.66, linetype = 2, 
                   color = "forestgreen", linewidth = 1) + # sublethal effects
        theme_bw() +
        theme(text = element_text(size = 25), 
              axis.text = element_text(size = 30, color = "black"), 
              plot.title = element_text(size = 17),
              legend.title = element_text(size = 20),
              legend.text = element_text(size = 20))
    )
      
    ggsave(filename = paste(species, sep = "_", "eDNA_DO_Temp_ScatterSize_23_mod.png"), 
           path = here("eDNA_Index_Hypoxia", "Plots", "DO_Temp_Scatter_23_mod"), 
           width = 2500, height = 2000, units = "px")
}
```

```{r}
# Add a gray background layer for all the environmental data

for (i in 1:length(dfsplit)) { # For each species: 
    species <- dfsplit[[i]]$Species[1] # Species name 
    title <- paste(species, sep = " ", "eDNA Index vs DO & Temperature (modeled)") # Plot title
    print(title)
    
# Plot + save
    
    print( # plot this species
      ggplot(data = envData, aes(x = Temp, y = DO)) +
        geom_point(color = "gray") +
        
        geom_point(data = dfsplit[[i]], aes(x = Temp, 
                                    y = DO, 
                                    size = eDNA_index, color = eDNA_index), 
                   alpha = 0.5) +
        scale_color_viridis_c(option = "viridis", direction = -1) + # color
        scale_size(range = c(2, 7)) +
        geom_point(data = dfsplit[[i]], aes(x = Temp, 
                                    y = DO, 
                                    size = eDNA_index, color = eDNA_index), 
                   shape = 1) + # add outline
        geom_point(data = dfsplit[[i]] %>% filter(eDNA_index == 0), 
                   aes(x = Temp, y = DO),
                   color = "black", size = 2) + # add more distinctive zeroes
        
        labs(x = "Temperature (C)", 
             y = "Dissolved Oxygen (mg/L)", 
             color = "eDNA Index", 
             size = "eDNA Index",
             title = title) +
        geom_hline(yintercept = 0.66, linetype = 2, 
                   color = "red", linewidth = 1) + # most die
        geom_hline(yintercept = 0.9, linetype = 2, 
                   color = "orange", linewidth = 1) + # ~50% die
        geom_hline(yintercept = 2.66, linetype = 2, 
                   color = "forestgreen", linewidth = 1) + # sublethal effects
        theme_bw() +
        theme(text = element_text(size = 25), 
              axis.text = element_text(size = 30, color = "black"), 
              plot.title = element_text(size = 17),
              legend.title = element_text(size = 20),
              legend.text = element_text(size = 20))
    )
      
    ggsave(filename = paste(species, sep = "_", "eDNA_DO_Temp_ScatterSize_AllBackground_23_mod.png"), 
           path = here("eDNA_Index_Hypoxia", "Plots", "DO_Temp_Scatter_23_mod"), 
           width = 2500, height = 2000, units = "px")
}
```

## DO vs. eDNA scatter plot

```{r}
# Distinguish the zero values better in the scatterplots
# I could do this by making a custom scale....ORRRR I could just add another layer where 0 is black lol :)

for (i in 1:length(dfsplit)) { # For each species: 
    species <- dfsplit[[i]]$Species[1] # Species name 
    title <- paste(species, sep = " ", "eDNA Index vs DO (modeled)") # Plot title
    print(title)
    
# Plot + save
    
    print( # plot this species
      ggplot(dfsplit[[i]], aes(x = DO, y = eDNA_index)) +
        geom_point(size = 2) +
        labs(x = "Dissolved Oxygen (mg/L)", 
             y = "eDNA Index", 
             title = title) +
        geom_vline(xintercept = 0.66, linetype = 2, 
                   color = "red", linewidth = 1) + # most die
        geom_vline(xintercept = 0.9, linetype = 2, 
                   color = "orange", linewidth = 1) + # ~50% die
        geom_vline(xintercept = 2.66, linetype = 2, 
                   color = "forestgreen", linewidth = 1) + # sublethal effects
        theme_bw() +
        theme(text = element_text(size = 25), 
              axis.text = element_text(size = 30, color = "black"), 
              plot.title = element_text(size = 17),
              legend.title = element_text(size = 20),
              legend.text = element_text(size = 20))
    )
      
    ggsave(filename = paste(species, sep = "_", "eDNA_DO_Scatter_23_mod.png"), 
           path = here("eDNA_Index_Hypoxia", "Plots", "eDNA_DO_Scatter_23_mod"), 
           width = 2500, height = 2000, units = "px")
}
```

## Heatmap

```{r}
for (i in 1:length(dfsplit)) { # For each species: 
  
    species <- dfsplit[[i]]$Species[1] # Species name 
    title <- paste(species, sep = " ", "eDNA Detection Density (modeled)") # Plot title
    print(title)
    
# Plot + save
    
    df <- dfsplit[[i]]

    df <- df %>% 
      drop_na(DO, Temp) %>% 
      relocate(DO, .after = Present) %>% 
      relocate(Temp, .after = DO) %>% 
      mutate(DO_bin = as.factor(round(DO*4) / 4)) %>% # note: these bins are CENTERED around a 0.5, so the actual range of the 1.0 bin is 0.75-1.25
      relocate(DO_bin, .after = DO) %>% 
      mutate(temperature_bin = as.factor(round(Temp*4) / 4)) %>% 
      relocate(temperature_bin, .after = Temp) 
    
    df_props <- df %>% 
      group_by(DO_bin, temperature_bin) %>% 
      dplyr::summarize(Samples = n(), Detections = sum(Present), Detected = Detections/Samples)
    
    # Now plot time
    
    print(ggplot(df_props, aes(x = DO_bin, y = temperature_bin, fill = Detected)) +
      geom_tile() +
      scale_fill_gradient(low = "skyblue", high = "darkblue") +
      ggtitle(title) +
      theme_bw())
      
    ggsave(filename = paste(species, sep = "_", "eDNA_Env_Density_23_mod.png"), 
           path = here("eDNA_Index_Hypoxia", "Plots", "eDNA_Env_Density_23_mod"), 
           width = 2500, height = 2000, units = "px")
}
```
