---
title: "Modeling with bmrs"
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse) # just like so much
library(patchwork) # put plots next to each other
library(scales)
library(ggrepel)
library(readxl)
library(here) # locating files
library(ggpmisc) # useful for annotations and models
library(modelr) # need for data_grid

# from andrew heiss
library(brms)             # Bayesian modeling through Stan
library(tidybayes)        # Manipulate Stan objects in a tidy way
library(broom)            # Convert model objects to data frames
library(broom.mixed)      # Convert brms model objects to data frames
library(betareg)          # Run beta regression models
library(extraDistr)       # Use extra distributions like dprop()
library(ggdist)           # Special geoms for posterior distributions
library(gghalves)         # Special half geoms
library(ggbeeswarm)       # Special distribution-shaped point jittering
library(patchwork)        # Combine ggplot objects
library(marginaleffects)  # Calculate marginal effects for regression models
library(modelsummary)     # Create side-by-side regression tables
```

```{r}
data <- read_csv(here("eDNA_Index_Hypoxia", "Data", "Copepod_eDNAindxEnvData_clean_no23.csv")) %>% # from ThesisGoal1.Rmd
  filter(!is.na(DO)) %>% 
  filter(Species == "Acartia longiremis") # you can change this to Oithona similis to check another species

# problem: can't handle 1 values. bc there aren't many, i'm gonna do the classic thing of "make it 0.999" lmao
data <- data %>% 
  mutate(eDNA_index = case_when(eDNA_index == 1 ~ 0.999999, .default = eDNA_index))

dataF <- data %>% filter(temperature < 10) # no outlier
```

Using [https://www.andrewheiss.com/blog/2021/11/08/beta-regression-guide/#zero-inflated-beta-regression-bayesian-style](this blog post)

Two models basically: 
1. Logistic regression model that predicts 0 or no 0
2. Beta regression model that predicts if it's 0-1

```{r, eval = F}
# First bit - prove it's working without zi

# make model
mod <- brm(
  bf(eDNA_index ~ DO, # main model
     phi ~ DO, # precision based on DO
     zi ~ 1), # zero/not zero process, currently ignoring
  data = data, 
  family = zero_inflated_beta()
)

# get coefficients
tidy(mod, effects = "fixed")

# intercept and DO are on a logit scale
# phi_Intercept and phi_DO are on a log scale
# zi intercept is on logit scale, so back-transform with plogis()
zi_intercept <- tidy(mod, effects = "fixed") %>% 
  filter(component == "zi", term == "(Intercept)") %>% 
  pull(estimate)

zi_intercept
plogis(zi_intercept) # 0.3, should be similar to prop of 0s in data

length(data$eDNA_index[data$eDNA_index == 0]) # 6 0s
length(data$eDNA_index) # 66 obs
6/66 # 0.09, same as plogis zi_intercept - yay! now to actually run the model w zi set

# example doesn't have zi X .o.
```

```{r}
# make model
mod <- brm(
  bf(eDNA_index ~ DO, # main model
     phi ~ DO, # precision based on DO
     zi ~ DO), # zero/not zero process
  data = data, 
  family = zero_inflated_beta()
)
```

```{r}
# get coefficients
tidy(mod, effects = "fixed")

# intercept and DO are on a logit scale
# phi_Intercept and phi_DO are on a log scale
# zi intercept is on logit scale, so back-transform with plogis()
# zi DO is also on logit scale, and we can combine the two zi effects

zi_intercept <- tidy(mod, effects = "fixed") %>% 
  filter(component == "zi", term == "(Intercept)") %>% 
  pull(estimate)

zi_quota <- tidy(mod, effects = "fixed") %>% 
  filter(component == "zi", term == "DO") %>% 
  pull(estimate)

plogis(zi_intercept + zi_quota) - plogis(zi_intercept)

# so, DO increasing reduces proportion of 0s by 13 percentage points. this makes sense.

# get predicted data
x_zip <- data$DO
do_pred <- tibble(DO = c(seq(0, max(x_zip), 0.1)))

pred_mod <- predictions(mod) # Outcome predicted by a fitted model on a specified scale for a given combination of values of the predictor variables, such as their observed values, their means, or factor levels (a.k.a. "reference grid").

ggplot(pred_mod, aes(x = DO, y = eDNA_index)) +
  geom_point() +
  theme_bw()

pred_mod_2 <- predictions(mod, newdata = do_pred)

ggplot(pred_mod_2, aes(x = DO, y = eDNA_index)) +
  geom_point() +
  theme_bw()

# https://mjskay.github.io/tidybayes/articles/tidy-brms.html Fit/prediction curves 
# Rather than calculating conditional means manually as in the previous example, we could use add_epred_draws(), which is analogous to brms::posterior_epred() (giving posterior draws from the expectation of the posterior predictive; i.e. posterior distributions of conditional means), but uses a tidy data format. We can combine it with modelr::data_grid() to first generate a grid describing the predictions we want, then transform that grid into a long-format data frame of draws from conditional means:

# plot conditional means
data %>% 
  data_grid(DO = seq_range(DO, n = 50)) %>% 
  add_epred_draws(mod) %>% 
  ggplot(aes(x = DO, y = eDNA_index)) +
  geom_point(data = data) +
  stat_lineribbon(aes(y = .epred), alpha = 0.5) + # from tidybayes, shows the summary of draws
  theme_bw()

# plot posterior predictions

data %>% 
  data_grid(DO = seq_range(DO, n = 50)) %>% 
  add_predicted_draws(mod) %>% 
  ggplot(aes(x = DO, y = eDNA_index)) +
  geom_point(data = data) +
  stat_lineribbon(aes(y = .prediction), .width = c(.95, .80, .50), alpha = 1/4) + # from tidybayes, shows the summary of draws
  theme_bw()
```

