---
title: "Zero-Inflated Beta Regressions"
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse) # just like so much
#library(patchwork) # put plots next to each other
library(scales)
#library(ggrepel)
#library(readxl)
library(here) # locating files
library(ggpmisc) # useful for annotations and models
library(modelr) # need for data_grid

# from andrew heiss
library(brms)             # Bayesian modeling through Stan
library(tidybayes)        # Manipulate Stan objects in a tidy way
library(broom)            # Convert model objects to data frames
library(broom.mixed)      # Convert brms model objects to data frames
#library(betareg)          # Run beta regression models
#library(extraDistr)       # Use extra distributions like dprop()
library(ggdist)           # Special geoms for posterior distributions
#library(gghalves)         # Special half geoms
#library(ggbeeswarm)       # Special distribution-shaped point jittering
#library(patchwork)        # Combine ggplot objects
#library(marginaleffects)  # Calculate marginal effects for regression models
#library(modelsummary)     # Create side-by-side regression tables
```

# Import data

```{r}
eDNAindxEnvData_cleanYr <- read_csv(here("eDNA_Index_Hypoxia", "Data", "Copepod_eDNAindxEnvData_clean_no23.csv")) %>% # from ThesisGoal1.Rmd
  filter(!is.na(DO)) %>% 
  filter(temperature < 11)

# Make a split version for looping over species
dfsplit <- split(eDNAindxEnvData_cleanYr, eDNAindxEnvData_cleanYr$Species) # Split by species
```

# Big Loop

```{r}
for (i in 1:length(dfsplit)) { # For each species: 
    species <- dfsplit[[i]]$Species[1] # Species name 
    sp_coeff <- paste(species, sep = "_", "coeffs") # name of output df
    sp_aic <- paste(species, sep = "_", "AIC")
    title <- paste(species) # Plot title
    print(title)
    
    data <- dfsplit[[i]] %>%
      mutate(eDNA_index = case_when(eDNA_index == 1 ~ 0.999999, .default = eDNA_index))
    
    dataF <- data %>% filter(temperature < 10) # no outlier
    
    # make the model
    mod <- brm(
      bf(eDNA_index ~ DO, # main model
         phi ~ DO, # precision based on DO
         zi ~ DO), # zero/not zero process
      data = dataF,
      family = zero_inflated_beta()
      )
    
    # get coefficients
    assign(sp_coeff, tidy(mod, effects = "fixed"))
    
    # get AIC
    # https://www.statology.org/aic-in-r/
    # AIC = 2K – 2ln(L)
    # K: The number of model parameters. The default value of K is 2, so a model with just one predictor variable will have a K value of 2+1 = 3.
    # K = 6 for this
    # ln(L): L = the maximum likelihood of the model. Most statistical software can automatically calculate this value for you.
    # https://rdrr.io/cran/brms/man/log_lik.brmsfit.html
    logLik <- max(log_lik(mod))

    AIC <- 2*6 - 2*logLik
    
    assign(sp_aic, AIC)
    
    # plot conditional means
    dataF %>%
      data_grid(DO = seq_range(DO, n = 50)) %>%
      add_epred_draws(mod) %>%
      ggplot(aes(x = DO, y = eDNA_index)) +
      geom_point(data = dataF) +
      stat_lineribbon(aes(y = .epred), alpha = 0.5) + # from tidybayes, shows the summary of draws
      labs(title = title, caption = "Conditional Means, TH042 Mooring") +
      ylab("eDNA Index") +
      theme_bw() +
      ylim(c(0,1)) +
      theme(axis.text = element_text(size = 35, color = "black"),
        axis.text.x = element_text(size = 25, hjust = 1, color = "black"),
        axis.title = element_text(size = 35, color = "black"),
        plot.title = element_text(size = 40),
        plot.caption = element_text(size = 20),
        legend.title = element_text(size = 35),
        legend.text = element_text(size = 35))
    
    ggsave(filename = paste(species, sep = "_", "ZOIB_Means_noOut.png"), 
           path = here("eDNA_Index_Hypoxia", "Plots", "ZOIB_Means_noOut_pub"), 
           width = 2500, height = 2000, units = "px")
    
    # plot posterior predictions
    dataF %>%
      data_grid(DO = seq_range(DO, n = 50)) %>%
      add_predicted_draws(mod) %>%
      ggplot(aes(x = DO, y = eDNA_index)) +
      geom_point(data = dataF) +
      stat_lineribbon(aes(y = .prediction), .width = c(.95, .80, .50), alpha = 1/4) + # from tidybayes, shows the summary of draws
      labs(title = title, caption = "Posterior Predictions") +
      theme_bw() +
      theme(axis.text = element_text(size = 35, color = "black"),
        axis.text.x = element_text(size = 25, hjust = 1, color = "black"),
        axis.title = element_text(size = 25, color = "black"),
        plot.title = element_text(size = 40),
        legend.title = element_text(size = 30),
        legend.text = element_text(size = 35)) 
    
    ggsave(filename = paste(species, sep = "_", "_ZOIB_Posterior_Predctions_noOut.png"), 
           path = here("eDNA_Index_Hypoxia", "Plots", "ZOIB_Posterior_Predictions_noOut"), 
           width = 2500, height = 2000, units = "px")

}
```


